const eventsdata = [
    {
      image: "https://www.bookeventz.com/blog/wp-content/uploads/2020/05/Summer-Pool-Party-Ideas.jpg",
      id:"1",
      title: "Pool Party",
      subTitle: "Pool Party",
      cost: "2400",
      duration: "Approx 2 night trip",
    },
    {
      image: "https://i.ytimg.com/vi/a9y7FEHaQVs/maxresdefault.jpg",
      id: "2",
      title: "Dance Concert",
      subTitle: "Dance Concert",
      cost: "5,200",
      duration: "Approx 2 night trip",
    },
    {
      image: "https://media.istockphoto.com/photos/cheering-crowd-of-unrecognized-people-at-a-rock-music-concert-concert-picture-id1189205501?k=20&m=1189205501&s=612x612&w=0&h=fexl_Cmu6AdLatIasGg_XYTkLSeWHCtvhMw1nK5_uDc=",
      id: "3",
      title: "Music Concert",
      subTitle: "Music Concert At Pune",
      cost: "45,500",
      duration: "Approx 2 night trip",
    },
    {
      image: "https://4.imimg.com/data4/FA/NN/MY-12958090/dj-service-500x500.jpeg",
      id: "4",
      title: "Dj Party",
      subTitle: "Exhibition",
      cost: "24,100",
      duration: "Approx 1 night trip",
    },
    {
      image: "http://s3.amazonaws.com/busites_www/kissonline/content/articles/newcastle.jpg",
      id: "5",
      title: "Band Concert",
      subTitle: "Bora Bora is a small South Pacific island northwest of",
      cost: "95,400",
      duration: "Approx 2 night 2 day trip",
    },
    {
      image: "https://wallup.net/wp-content/uploads/2019/10/86222-kataklysm-death-metal-heavy-hard-rock-concert-concerts-guitar-guitars-1-748x499.jpg",
      id: "6",
      title: "Rock Concert",
      subTitle: "London, the capital of England and the United",
      cost: "38,800",
      duration: "Approx 3 night 2 day trip",
    },
  ]
  export default eventsdata;