const gallerydata =[
    {
      image: "https://i.ytimg.com/vi/a9y7FEHaQVs/maxresdefault.jpg",
      id:"1",
      title: "Dance Concert",
      subTitle: "Singapore, officialy thr Republic of Singapore, is a",
      cost: "38,800",
      duration: "Approx 2 night trip",
    },
    {
      image: "https://gossipkigalliyan.com/wp-content/uploads/2019/06/58049151_871409649864563_6469656868875665408_n.jpg",
      id: "2",
      title: "Pupper Party",
      subTitle: "Thailand is a Southeast Asia country. It's known for",
      cost: "54,200",
      duration: "Approx 2 night trip",
    },
    {
      image: "https://media.istockphoto.com/photos/cheering-crowd-of-unrecognized-people-at-a-rock-music-concert-concert-picture-id1189205501?k=20&m=1189205501&s=612x612&w=0&h=fexl_Cmu6AdLatIasGg_XYTkLSeWHCtvhMw1nK5_uDc=",
      id: "3",
      title: "Music Concert",
      subTitle: "Music Concert At Pune",
      cost: "45,500",
      duration: "Approx 2 night trip",
    },
    {
      image: "https://adventuresome.in/wp-content/uploads/2019/08/jumping-from-sky-min-1280x720.jpg",
      id: "4",
      title: "SKYDIVING",
      subTitle: "New Zealand is an island country in the",
      cost: "24,100",
      duration: "Approx 1 night trip",
    },
    {
      image: "https://images.hindustantimes.com/rf/image_size_630x354/HT/p2/2019/12/21/Pictures/ht-pune_bcdb9156-23de-11ea-b71b-55a416c89533.jpg",
      id: "5",
      title: "Rose exhibition",
      subTitle: "Bora Bora is a small South Pacific island northwest of",
      cost: "95,400",
      duration: "Approx 2 night 2 day trip",
    },
    {
      image: "https://wallup.net/wp-content/uploads/2019/10/86222-kataklysm-death-metal-heavy-hard-rock-concert-concerts-guitar-guitars-1-748x499.jpg",
      id: "6",
      title: "Rock Concert",
      subTitle: "London, the capital of England and the United",
      cost: "38,800",
      duration: "Approx 3 night 2 day trip",
    },
  ]
  export default gallerydata;